version: '3'

services:
  web:
    container_name: cms_web_container
    restart: always
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: cms_db_container
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cms@123
      - POSTGRES_DB=cms_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"